name    'counsyl-packer'
version '0.9.6'
source  'git://github.com/counsyl/puppet-packer.git'
author  'Counsyl, Inc.'
license 'Apache License, Version 2.0'
summary 'Puppet module for installing Packer, the modern automated machine image creation tool.'
description 'Puppet module for installing Packer, the modern automated machine image creation tool.'
project_page 'https://github.com/counsyl/puppet-packer'

dependency 'counsyl/sys', '>= 0.9.1'
